# Generated by Django 4.2.6 on 2024-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0004_gamereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='content',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='game',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='game_name',
            field=models.CharField(default='Unknown Game', max_length=100),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='genre',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='hours_played',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='platform',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='thumbs_up',
            field=models.BooleanField(default=True),
        ),
    ]
